### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by jgcmarins** [Maronato/maro_auth#1]
Cara, tudo bem?
Você poderia compartilhar sua fonte de aprendizado? hehe
Valeu! Abraço!

**Comment by Maronato** [comment]
Nossa cara eu nem sei dizer. Você se refere a Python ou a django? 
Nos dois eu aprendi lendo a documentação e pesquisando no stackoverflow. 

Se você tiver problemas em aprender alguma coisa fala o que é que eu tento te dar as dicas, mas acredite que não é nenhum site ou tutorial obscuro hahaha!

**Comment by jgcmarins** [comment]
Saquei!

Me refiro ao django mesmo. To começando agora e tipo, não é nada específico, mas quando eu estou implementando algo, eu procuro referências na internet e não encontro muita informação sobe o que seria uma "good practice" daquilo que eu to fazendo. Dai sempre fico com a sensação de que to fazendo gambiarra! hahahaha

Mas valeu, mano! Se eu tiver alguma dúvida específica, te dou um toque. Acho que vou dar uma estudada nesse seu repo. Gostei de como você implementou.

Abraço!
